### ISSUE TITLE
problems list

### ISSUE THREAD

**Issue by Jayin** [Jayin/SiyuanGroup#26]
All Http request:
in Application.oncreate() call RestClient.init();

圈子系统
1.圈子系统漏了“退出该圈”  
   圈子系统理论上支持退出该圈子，但是文档没说
2.为了简化流程  “转让圈子” 暂时不做 后期做
3.圈子可以发起活动，在主页的活动只能查看/报名活动 而且活动有权限。

API Note:
 1.UserAPI  
      getAllMember（）   这里分页，如果页数大于实际有的页数 ，返回是{"users":[]}

关于icon设计
  大小为48*48
需要一张pic:
  校友录的主题字

Todo:
1. ic_acty_head_back_small ---->>  ic_acty_head_back_big 

To Vector：
1.加入了一个常用的MyProgressDialog(使用setText()可以刷新当前状态,)

**Comment by VectorWen** [comment]
四大四大····而非似懂非懂是

**Comment by FvckSh1t** [comment]
nice, 英爷目前我们应该只做jpg头像支持, 为了方便 :)

**Comment by Jayin** [comment]
廉温我更新了。加入了一个常用的MyProgressDialog(使用setText()可以刷新当前状态,)  
好处就是旋转的progress 不在卡了。。

**Comment by Jayin** [comment]
update information：3.圈子可以发起活动，在主页的活动只能查看/报名活动 而且活动有权限。

**Comment by FvckSh1t** [comment]
nice
